spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create-drop
  show-sql: true
  generate-ddl: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://host.docker.internal:5432/postsdb
  username: root
  password: root